services:
  rezeptor:
    build: .
    image: rezeptor:latest
    container_name: rezeptor
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    ports:
      - "88:8000"
    volumes:
      - /volume1/docker/rezept0r/tmp:/app/tmp
      - /volume1/docker/rezept0r/data:/app/data
    mem_limit: 512m
    memswap_limit: 512m   # No swap – protect SD card
